# Importando as bibliotecas

In [1]:
import pandas as pd 
import matplotlib.pyplot as plt 
import seaborn  as sns 
import plotly as px 
import numpy as np 
import psycopg2

# Carregando os dados

## Clientes

In [2]:
clientes = pd.read_csv(r'C:\Users\walle\OneDrive\Área de Trabalho\Projetos DataScience\Projeto Ecomerce Olist\Dados\olist_customers_dataset.csv')
clientes.head()

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,14409,franca,SP
1,18955e83d337fd6b2def6b18a428ac77,290c77bc529b7ac935b93aa66c333dc3,9790,sao bernardo do campo,SP
2,4e7b3e00288586ebd08712fdd0374a03,060e732b5b29e8181a18229c7b0b2b5e,1151,sao paulo,SP
3,b2b6027bc5c5109e529d4dc6358b12c3,259dac757896d24d7702b9acbbff3f3c,8775,mogi das cruzes,SP
4,4f2d8ab171c80ec8364f7c12e35b23ad,345ecd01c38d18a9036ed96c73b8d066,13056,campinas,SP

In [3]:
clientes.info()

<class 'pandas.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 5 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   customer_id               99441 non-null  str
 1   customer_unique_id        99441 non-null  str
 2   customer_zip_code_prefix  99441 non-null  int64
 3   customer_city             99441 non-null  str
 4   customer_state            99441 non-null  str
dtypes: int64(1), str(4)
memory usage: 3.8 MB

## Geolocalização

In [4]:
geo_localiza = pd.read_csv(r'C:\Users\walle\OneDrive\Área de Trabalho\Projetos DataScience\Projeto Ecomerce Olist\Dados\olist_geolocation_dataset.csv')
geo_localiza.head()

,geolocation_zip_code_prefix,geolocation_lat,geolocation_lng,geolocation_city,geolocation_state
0,1037,-23.545621,-46.639292,sao paulo,SP
1,1046,-23.546081,-46.644820,sao paulo,SP
2,1046,-23.546129,-46.642951,sao paulo,SP
3,1041,-23.544392,-46.639499,sao paulo,SP
4,1035,-23.541578,-46.641607,sao paulo,SP

In [5]:
geo_localiza.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000163 entries, 0 to 1000162
Data columns (total 5 columns):
 #   Column                       Non-Null Count    Dtype
---  ------                       --------------    -----
 0   geolocation_zip_code_prefix  1000163 non-null  int64
 1   geolocation_lat              1000163 non-null  float64
 2   geolocation_lng              1000163 non-null  float64
 3   geolocation_city             1000163 non-null  str
 4   geolocation_state            1000163 non-null  str
dtypes: float64(2), int64(1), str(2)
memory usage: 38.2 MB

## Ordem items

In [6]:
ordem_itemns  = pd.read_csv(r'C:\Users\walle\OneDrive\Área de Trabalho\Projetos DataScience\Projeto Ecomerce Olist\Dados\olist_order_items_dataset.csv')
ordem_itemns.head()

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.90,13.29
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03 11:05:13,239.90,19.93
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,2018-01-18 14:48:30,199.00,17.87
3,00024acbcdf0a6daa1e931b038114c75,1,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,2018-08-15 10:10:18,12.99,12.79
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,2017-02-13 13:57:51,199.90,18.14

In [7]:
ordem_itemns.info()

<class 'pandas.DataFrame'>
RangeIndex: 112650 entries, 0 to 112649
Data columns (total 7 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   order_id             112650 non-null  str
 1   order_item_id        112650 non-null  int64
 2   product_id           112650 non-null  str
 3   seller_id            112650 non-null  str
 4   shipping_limit_date  112650 non-null  str
 5   price                112650 non-null  float64
 6   freight_value        112650 non-null  float64
dtypes: float64(2), int64(1), str(4)
memory usage: 6.0 MB

## Ordem pagamentos

In [8]:
Ordem_pagamentos = pd.read_csv(r'C:\Users\walle\OneDrive\Área de Trabalho\Projetos DataScience\Projeto Ecomerce Olist\Dados\olist_order_payments_dataset.csv')
Ordem_pagamentos.head()

,order_id,payment_sequential,payment_type,payment_installments,payment_value
0,b81ef226f3fe1789b1e8b2acac839d17,1,credit_card,8,99.33
1,a9810da82917af2d9aefd1278f1dcfa0,1,credit_card,1,24.39
2,25e8ea4e93396b6fa0d3dd708e76c1bd,1,credit_card,1,65.71
3,ba78997921bbcdc1373bb41e913ab953,1,credit_card,8,107.78
4,42fdf880ba16b47b59251dd489d4441a,1,credit_card,2,128.45

In [9]:
Ordem_pagamentos.info()

<class 'pandas.DataFrame'>
RangeIndex: 103886 entries, 0 to 103885
Data columns (total 5 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   order_id              103886 non-null  str
 1   payment_sequential    103886 non-null  int64
 2   payment_type          103886 non-null  str
 3   payment_installments  103886 non-null  int64
 4   payment_value         103886 non-null  float64
dtypes: float64(1), int64(2), str(2)
memory usage: 4.0 MB

## Ordem comentarios

In [10]:
ordem_cometarios = pd.read_csv(r'C:\Users\walle\OneDrive\Área de Trabalho\Projetos DataScience\Projeto Ecomerce Olist\Dados\olist_order_reviews_dataset.csv')
ordem_cometarios.head()

,review_id,order_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp
0,7bc2406110b926393aa56f80a40eba40,73fc7af87114b39712e6da79b0a377eb,4,NaN,NaN,2018-01-18 00:00:00,2018-01-18 21:46:59
1,80e641a11e56f04c1ad469d5645fdfde,a548910a1c6147796b98fdf73dbeba33,5,NaN,NaN,2018-03-10 00:00:00,2018-03-11 03:05:13
2,228ce5500dc1d8e020d8d1322874b6f0,f9e4b658b201a9f2ecdecbb34bed034b,5,NaN,NaN,2018-02-17 00:00:00,2018-02-18 14:36:24
3,e64fb393e7b32834bb789ff8bb30750e,658677c97b385a9be170737859d3511b,5,NaN,Recebi bem antes do prazo estipulado.,2017-04-21 00:00:00,2017-04-21 22:02:06
4,f7c4243c7fe1938f181bec41a392bdeb,8e6bfb81e283fa7e4f11123a3fb894f1,5,NaN,Parabéns lojas lannister adorei comprar pela I...,2018-03-01 00:00:00,2018-03-02 10:26:53

In [11]:
ordem_cometarios.info()

<class 'pandas.DataFrame'>
RangeIndex: 99224 entries, 0 to 99223
Data columns (total 7 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   review_id                99224 non-null  str
 1   order_id                 99224 non-null  str
 2   review_score             99224 non-null  int64
 3   review_comment_title     11568 non-null  str
 4   review_comment_message   40977 non-null  str
 5   review_creation_date     99224 non-null  str
 6   review_answer_timestamp  99224 non-null  str
dtypes: int64(1), str(6)
memory usage: 5.3 MB

## Ordens conjuntos de dados

In [12]:
ordens_conjun_dados = pd.read_csv(r'C:\Users\walle\OneDrive\Área de Trabalho\Projetos DataScience\Projeto Ecomerce Olist\Dados\olist_orders_dataset.csv')
ordens_conjun_dados.head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15 00:00:00
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26 00:00:00

In [13]:
ordens_conjun_dados.info()

<class 'pandas.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 8 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   order_id                       99441 non-null  str
 1   customer_id                    99441 non-null  str
 2   order_status                   99441 non-null  str
 3   order_purchase_timestamp       99441 non-null  str
 4   order_approved_at              99281 non-null  str
 5   order_delivered_carrier_date   97658 non-null  str
 6   order_delivered_customer_date  96476 non-null  str
 7   order_estimated_delivery_date  99441 non-null  str
dtypes: str(8)
memory usage: 6.1 MB

## Produtos conjunto de dados

In [14]:
produt_conjun_dados = pd.read_csv(r'C:\Users\walle\OneDrive\Área de Trabalho\Projetos DataScience\Projeto Ecomerce Olist\Dados\olist_products_dataset.csv')
produt_conjun_dados.head()

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
0,1e9e8ef04dbcff4541ed26657ea517e5,perfumaria,40.0,287.0,1.0,225.0,16.0,10.0,14.0
1,3aa071139cb16b67ca9e5dea641aaa2f,artes,44.0,276.0,1.0,1000.0,30.0,18.0,20.0
2,96bd76ec8810374ed1b65e291975717f,esporte_lazer,46.0,250.0,1.0,154.0,18.0,9.0,15.0
3,cef67bcfe19066a932b7673e239eb23d,bebes,27.0,261.0,1.0,371.0,26.0,4.0,26.0
4,9dc1a7de274444849c219cff195d0b71,utilidades_domesticas,37.0,402.0,4.0,625.0,20.0,17.0,13.0

In [15]:
produt_conjun_dados.info()

<class 'pandas.DataFrame'>
RangeIndex: 32951 entries, 0 to 32950
Data columns (total 9 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   product_id                  32951 non-null  str
 1   product_category_name       32341 non-null  str
 2   product_name_lenght         32341 non-null  float64
 3   product_description_lenght  32341 non-null  float64
 4   product_photos_qty          32341 non-null  float64
 5   product_weight_g            32949 non-null  float64
 6   product_length_cm           32949 non-null  float64
 7   product_height_cm           32949 non-null  float64
 8   product_width_cm            32949 non-null  float64
dtypes: float64(7), str(2)
memory usage: 2.3 MB

## Vendedores conjunto de dados

In [16]:
vendedores_conjun_dados = pd.read_csv(r'C:\Users\walle\OneDrive\Área de Trabalho\Projetos DataScience\Projeto Ecomerce Olist\Dados\olist_sellers_dataset.csv')
vendedores_conjun_dados.head()

,seller_id,seller_zip_code_prefix,seller_city,seller_state
0,3442f8959a84dea7ee197c632cb2df15,13023,campinas,SP
1,d1b65fc7debc3361ea86b5f14c68d2e2,13844,mogi guacu,SP
2,ce3ad9de960102d0677a81f5d0bb7b2d,20031,rio de janeiro,RJ
3,c0f3eea2e14555b6faeea3dd58c1b1c3,4195,sao paulo,SP
4,51a04a8a6bdcb23deccc82b0b80742cf,12914,braganca paulista,SP

In [17]:
vendedores_conjun_dados.info()

<class 'pandas.DataFrame'>
RangeIndex: 3095 entries, 0 to 3094
Data columns (total 4 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   seller_id               3095 non-null   str
 1   seller_zip_code_prefix  3095 non-null   int64
 2   seller_city             3095 non-null   str
 3   seller_state            3095 non-null   str
dtypes: int64(1), str(3)
memory usage: 96.8 KB

## Produtos categorias nomes transações

In [18]:
Produt_categ_nome_transacao = pd.read_csv(r'C:\Users\walle\OneDrive\Área de Trabalho\Projetos DataScience\Projeto Ecomerce Olist\Dados\product_category_name_translation.csv')
Produt_categ_nome_transacao.head()

    product_category_name product_category_name_english
0            beleza_saude                 health_beauty
1  informatica_acessorios         computers_accessories
2              automotivo                          auto
3         cama_mesa_banho                bed_bath_table
4        moveis_decoracao               furniture_decor

In [19]:
Produt_categ_nome_transacao.info()

<class 'pandas.DataFrame'>
RangeIndex: 71 entries, 0 to 70
Data columns (total 2 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   product_category_name          71 non-null     str
 1   product_category_name_english  71 non-null     str
dtypes: str(2)
memory usage: 1.2 KB

# Analisando e tratando os dados

##  Anali. conjunto clientes

In [20]:
clientes.head()

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,14409,franca,SP
1,18955e83d337fd6b2def6b18a428ac77,290c77bc529b7ac935b93aa66c333dc3,9790,sao bernardo do campo,SP
2,4e7b3e00288586ebd08712fdd0374a03,060e732b5b29e8181a18229c7b0b2b5e,1151,sao paulo,SP
3,b2b6027bc5c5109e529d4dc6358b12c3,259dac757896d24d7702b9acbbff3f3c,8775,mogi das cruzes,SP
4,4f2d8ab171c80ec8364f7c12e35b23ad,345ecd01c38d18a9036ed96c73b8d066,13056,campinas,SP

In [21]:
clientes.info()

<class 'pandas.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 5 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   customer_id               99441 non-null  str
 1   customer_unique_id        99441 non-null  str
 2   customer_zip_code_prefix  99441 non-null  int64
 3   customer_city             99441 non-null  str
 4   customer_state            99441 non-null  str
dtypes: int64(1), str(4)
memory usage: 3.8 MB

In [22]:
clientes.duplicated().sum()

np.int64(0)

In [23]:
clientes.isnull().sum()

customer_id                 0
customer_unique_id          0
customer_zip_code_prefix    0
customer_city               0
customer_state              0
dtype: int64

In [24]:
clientes['customer_state'].unique()

<StringArray>
['SP', 'SC', 'MG', 'PR', 'RJ', 'RS', 'PA', 'GO', 'ES', 'BA', 'MA', 'MS', 'CE',
 'DF', 'RN', 'PE', 'MT', 'AM', 'AP', 'AL', 'RO', 'PB', 'TO', 'PI', 'AC', 'SE',
 'RR']
Length: 27, dtype: str

In [25]:
clientes['customer_city'].unique()

<StringArray>
[               'franca', 'sao bernardo do campo',             'sao paulo',
       'mogi das cruzes',              'campinas',        'jaragua do sul',
               'timoteo',              'curitiba',        'belo horizonte',
         'montes claros',
 ...
              'balbinos',          'serra bonita',          'venda branca',
           'sanga puita',               'queiroz',                'siriji',
   'natividade da serra',          'monte bonito',            'sao rafael',
     'eugenio de castro']
Length: 4119, dtype: str

### Resultados

**Sobre as colunas do DF**

* Coluna **customer_id**:
Representa o Id de cada pedido.

* Coluna **customer_unique_id**:
Representa o id unico de cada cliete.

* Coluna **customer_zip_code_prefix**:
Representa o prefixo do CEP, que serve para identificar a região aproximada do cliente

* Coluna **customer_city**:
Representa a cidade do cliente.
* Coluna **customer_state**.
Representa o estado do cliente.

**Conclusão**

Pelo o que analisei nesse DF não a necessidade de modificar os dados ou fazer tratamentos, pois todas as colunas estão com o tipo coreto de dados, não possui valores duplicados ou nulos, e todas as colunas parecem fazer sentido em relação ao seu nome e conteudo.

## Anali. conjunto geolocalização

In [26]:
geo_localiza.head()

,geolocation_zip_code_prefix,geolocation_lat,geolocation_lng,geolocation_city,geolocation_state
0,1037,-23.545621,-46.639292,sao paulo,SP
1,1046,-23.546081,-46.644820,sao paulo,SP
2,1046,-23.546129,-46.642951,sao paulo,SP
3,1041,-23.544392,-46.639499,sao paulo,SP
4,1035,-23.541578,-46.641607,sao paulo,SP

In [27]:
geo_localiza.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000163 entries, 0 to 1000162
Data columns (total 5 columns):
 #   Column                       Non-Null Count    Dtype
---  ------                       --------------    -----
 0   geolocation_zip_code_prefix  1000163 non-null  int64
 1   geolocation_lat              1000163 non-null  float64
 2   geolocation_lng              1000163 non-null  float64
 3   geolocation_city             1000163 non-null  str
 4   geolocation_state            1000163 non-null  str
dtypes: float64(2), int64(1), str(2)
memory usage: 38.2 MB

In [28]:
geo_localiza.duplicated().sum()

np.int64(261831)

In [29]:
geo_localiza = geo_localiza.drop_duplicates()

In [30]:
geo_localiza.isnull().sum()

geolocation_zip_code_prefix    0
geolocation_lat                0
geolocation_lng                0
geolocation_city               0
geolocation_state              0
dtype: int64

### Resultados

**Sobre as colunas do DF**

* Coluna **geolocation_zip_code_prefix**:
Representa o prefixo do CEP associado à localização geográfica de um registro.

* Coluna **geolocation_lat**:
Representa a latitude.

* Coluna **geolocation_lng**:
Representa a longitude.

* Coluna **geolocation_city**:
Representa a cidade da geolacalização.

* Coluna **geolocation_state**:
Representa o estado da geolocalização.

**Conclusão**

As colunas estavão com os tipos de dados certos, o nome esta com uma representação correta em relação aos dados, não possui dados nulos, mas tinha a presença de dados duplicados, removi todos com o metodo drop_duplicates

## Anali. conjunto ordem_itemns

In [31]:
ordem_itemns.head()

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.90,13.29
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03 11:05:13,239.90,19.93
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,2018-01-18 14:48:30,199.00,17.87
3,00024acbcdf0a6daa1e931b038114c75,1,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,2018-08-15 10:10:18,12.99,12.79
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,2017-02-13 13:57:51,199.90,18.14

In [32]:
ordem_itemns.info()

<class 'pandas.DataFrame'>
RangeIndex: 112650 entries, 0 to 112649
Data columns (total 7 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   order_id             112650 non-null  str
 1   order_item_id        112650 non-null  int64
 2   product_id           112650 non-null  str
 3   seller_id            112650 non-null  str
 4   shipping_limit_date  112650 non-null  str
 5   price                112650 non-null  float64
 6   freight_value        112650 non-null  float64
dtypes: float64(2), int64(1), str(4)
memory usage: 6.0 MB

In [33]:
ordem_itemns['shipping_limit_date'] = pd.to_datetime(ordem_itemns['shipping_limit_date'])

In [34]:
ordem_itemns.isnull().sum()

order_id               0
order_item_id          0
product_id             0
seller_id              0
shipping_limit_date    0
price                  0
freight_value          0
dtype: int64

In [35]:
ordem_itemns.duplicated().sum()

np.int64(0)

### Resultado

**Sobre as colunas do DF**
* Coluna **order_id**:
Representa o Id unico de cada pedido realizado.

* Coluna **order_item_id**:
Representa o ID de cada item dentro de um pedido.

* Coluna **product_id**:
Representa o Id de cada produto dentro do pedido.

* Coluna **seller_id**:
Representa o identificador unico do vendedor de cada pedido.

* Coluna **hipping_limit_date**:
Representa a data limite que um pedido deve ser enviado por um vendedor.

* Coluna **price**: representa o preço do item.

* Coluna **freight_value**:
Representa o valor do frete cobrado para o envio do pedido.

**Conclusão**

Quase todas as colunas estavam com o tipo correto de dados, exceto a coluna hipping_limit_date, que estava com o tipo STR, mudeu seu tipo para Datetime64 e deixei no formato padrão do US, o conjunto não possui dados nulos o duplicados.

## Anali. conjunto ordem_pagamentos

In [36]:
Ordem_pagamentos.head()

,order_id,payment_sequential,payment_type,payment_installments,payment_value
0,b81ef226f3fe1789b1e8b2acac839d17,1,credit_card,8,99.33
1,a9810da82917af2d9aefd1278f1dcfa0,1,credit_card,1,24.39
2,25e8ea4e93396b6fa0d3dd708e76c1bd,1,credit_card,1,65.71
3,ba78997921bbcdc1373bb41e913ab953,1,credit_card,8,107.78
4,42fdf880ba16b47b59251dd489d4441a,1,credit_card,2,128.45

In [37]:
Ordem_pagamentos.info()

<class 'pandas.DataFrame'>
RangeIndex: 103886 entries, 0 to 103885
Data columns (total 5 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   order_id              103886 non-null  str
 1   payment_sequential    103886 non-null  int64
 2   payment_type          103886 non-null  str
 3   payment_installments  103886 non-null  int64
 4   payment_value         103886 non-null  float64
dtypes: float64(1), int64(2), str(2)
memory usage: 4.0 MB

In [38]:
Ordem_pagamentos.isnull().sum()

order_id                0
payment_sequential      0
payment_type            0
payment_installments    0
payment_value           0
dtype: int64

In [39]:
Ordem_pagamentos.duplicated().sum()

np.int64(0)

### Resultado

**Sobre as colunas do DF**

* Coluna **order_id**:
Representa o identificador unico do pedido.

* Coluna **payment_sequential**:
Representa a sequência da parcela que está sendo paga, no registro especifico.

* Coluna **payment_type**:
Representa o tipo de pagamento, debito, credito e etc.

* Coluna **payment_installments**:
Representa o número total de parcelas que o pedido foi dividido, se for a vista é 1.

* Coluna **payment_value**:
Representa o valor a ser pago.

**Conclusão**

Todas as colunas estão com o tipo correto de dados, e não possuem valores nulos ou duplicados.

## Anali. conjunto ordem_comentarios

In [40]:
ordem_cometarios.head()

,review_id,order_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp
0,7bc2406110b926393aa56f80a40eba40,73fc7af87114b39712e6da79b0a377eb,4,NaN,NaN,2018-01-18 00:00:00,2018-01-18 21:46:59
1,80e641a11e56f04c1ad469d5645fdfde,a548910a1c6147796b98fdf73dbeba33,5,NaN,NaN,2018-03-10 00:00:00,2018-03-11 03:05:13
2,228ce5500dc1d8e020d8d1322874b6f0,f9e4b658b201a9f2ecdecbb34bed034b,5,NaN,NaN,2018-02-17 00:00:00,2018-02-18 14:36:24
3,e64fb393e7b32834bb789ff8bb30750e,658677c97b385a9be170737859d3511b,5,NaN,Recebi bem antes do prazo estipulado.,2017-04-21 00:00:00,2017-04-21 22:02:06
4,f7c4243c7fe1938f181bec41a392bdeb,8e6bfb81e283fa7e4f11123a3fb894f1,5,NaN,Parabéns lojas lannister adorei comprar pela I...,2018-03-01 00:00:00,2018-03-02 10:26:53

In [41]:
ordem_cometarios['review_score'].unique()

array([4, 5, 1, 3, 2])

In [42]:
ordem_cometarios.info()

<class 'pandas.DataFrame'>
RangeIndex: 99224 entries, 0 to 99223
Data columns (total 7 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   review_id                99224 non-null  str
 1   order_id                 99224 non-null  str
 2   review_score             99224 non-null  int64
 3   review_comment_title     11568 non-null  str
 4   review_comment_message   40977 non-null  str
 5   review_creation_date     99224 non-null  str
 6   review_answer_timestamp  99224 non-null  str
dtypes: int64(1), str(6)
memory usage: 5.3 MB

In [43]:
ordem_cometarios['review_creation_date'] = pd.to_datetime(ordem_cometarios['review_creation_date'])
ordem_cometarios['review_answer_timestamp'] = pd.to_datetime(ordem_cometarios['review_answer_timestamp'])

In [44]:
ordem_cometarios.isnull().sum()

review_id                      0
order_id                       0
review_score                   0
review_comment_title       87656
review_comment_message     58247
review_creation_date           0
review_answer_timestamp        0
dtype: int64

In [45]:
ordem_cometarios['review_comment_title'] = ordem_cometarios['review_comment_title'].fillna('titulo não informado')
ordem_cometarios['review_comment_message'] = ordem_cometarios['review_comment_message'].fillna('sem comentario')

In [46]:
ordem_cometarios.duplicated().sum()

np.int64(0)

### Resultado

**Sobre as colunas do DF**

* Coluna **review_id**:
Representa o Id unico d e cada avaliação ou comentario. 

* Coluna **order_id**:
Representa o ID unico de cada pedido

* Coluna **review_score**:
Representa o grau de satisfação, que vai de 1 a 5.

* Coluna **review_comment_title**:
Representa o titulo dos comentarios.

* Coluna **review_comment_message**:
Representa a menssagem do comentario

* Coluna **review_creation_date**:
Representa a data que a avaliação ou comentario foi criado.

* Coluna **review_answer_timestamp**:
Indica a data e a hora em que o vendedor ou a empresa respondeu a avaliação feita pelo cliente

**Conclusão**

As colunas **review_creation_date**  e **review_answer_timestamp** estavão com os tipos de dados errados, ajustei para o tipo correto, nenhuma coluna possui valores duplicados, porem as colunas **review_comment_title** e **review_comment_message**,possuiam valores nulos, como se tratavam de informações a respeito dos titulos e mensagens dos comentarios, achei melhor não remover as linhas, pois ainda poderia utilizar as informaçoes, por exemplo de **review_score**, por isso só informei que a linha estava sem titulo e/ou sem mensagem, mas mantive no DF.

## Anali. conjunto ordens_conjun_dados

In [47]:
ordens_conjun_dados.head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15 00:00:00
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26 00:00:00

In [48]:
ordens_conjun_dados['order_status'].unique()

<StringArray>
[  'delivered',    'invoiced',     'shipped',  'processing', 'unavailable',
    'canceled',     'created',    'approved']
Length: 8, dtype: str

In [49]:
ordens_conjun_dados.info()

<class 'pandas.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 8 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   order_id                       99441 non-null  str
 1   customer_id                    99441 non-null  str
 2   order_status                   99441 non-null  str
 3   order_purchase_timestamp       99441 non-null  str
 4   order_approved_at              99281 non-null  str
 5   order_delivered_carrier_date   97658 non-null  str
 6   order_delivered_customer_date  96476 non-null  str
 7   order_estimated_delivery_date  99441 non-null  str
dtypes: str(8)
memory usage: 6.1 MB

In [50]:
ordens_conjun_dados['order_purchase_timestamp'] = pd.to_datetime(ordens_conjun_dados['order_purchase_timestamp'])
ordens_conjun_dados['order_approved_at'] = pd.to_datetime(ordens_conjun_dados['order_approved_at'])
ordens_conjun_dados['order_delivered_carrier_date'] = pd.to_datetime(ordens_conjun_dados['order_delivered_carrier_date'])
ordens_conjun_dados['order_delivered_customer_date'] = pd.to_datetime(ordens_conjun_dados['order_delivered_customer_date'])
ordens_conjun_dados['order_estimated_delivery_date'] = pd.to_datetime(ordens_conjun_dados['order_estimated_delivery_date'])

In [51]:
ordens_conjun_dados.isnull().sum()

order_id                            0
customer_id                         0
order_status                        0
order_purchase_timestamp            0
order_approved_at                 160
order_delivered_carrier_date     1783
order_delivered_customer_date    2965
order_estimated_delivery_date       0
dtype: int64

In [52]:
df_nulos = ordens_conjun_dados[
    ordens_conjun_dados['order_approved_at'].isna()]
df_nulos.head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
1130,00b1cb0320190ca0daa2c88b35206009,3532ba38a3fd242259a514ac2b6ae6b6,canceled,2018-08-28 15:26:39,NaT,NaT,NaT,2018-09-12
1801,ed3efbd3a87bea76c2812c66a0b32219,191984a8ba4cbb2145acb4fe35b69664,canceled,2018-09-20 13:54:16,NaT,NaT,NaT,2018-10-17
1868,df8282afe61008dc26c6c31011474d02,aa797b187b5466bc6925aaaa4bb3bed1,canceled,2017-03-04 12:14:30,NaT,NaT,NaT,2017-04-10
2029,8d4c637f1accf7a88a4555f02741e606,b1dd715db389a2077f43174e7a675d07,canceled,2018-08-29 16:27:49,NaT,NaT,NaT,2018-09-13
2161,7a9d4c7f9b068337875b95465330f2fc,7f71ae48074c0cfec9195f88fcbfac55,canceled,2017-05-01 16:12:39,NaT,NaT,NaT,2017-05-30

In [53]:
df_nulos['order_status'].unique()

<StringArray>
['canceled', 'delivered', 'created']
Length: 3, dtype: str

In [54]:
df_nulos_filtro_delive = df_nulos[df_nulos['order_status'] == 'delivered']
df_nulos_filtro_delive

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
5323,e04abd8149ef81b95221e88f6ed9ab6a,2127dc6603ac33544953ef05ec155771,delivered,2017-02-18 14:40:00,NaT,2017-02-23 12:04:47,2017-03-01 13:25:33,2017-03-17
16567,8a9adc69528e1001fc68dd0aaebbb54a,4c1ccc74e00993733742a3c786dc3c1f,delivered,2017-02-18 12:45:31,NaT,2017-02-23 09:01:52,2017-03-02 10:05:06,2017-03-21
19031,7013bcfc1c97fe719a7b5e05e61c12db,2941af76d38100e0f8740a374f1a5dc3,delivered,2017-02-18 13:29:47,NaT,2017-02-22 16:25:25,2017-03-01 08:07:38,2017-03-17
22663,5cf925b116421afa85ee25e99b4c34fb,29c35fc91fc13fb5073c8f30505d860d,delivered,2017-02-18 16:48:35,NaT,2017-02-22 11:23:10,2017-03-09 07:28:47,2017-03-31
23156,12a95a3c06dbaec84bcfb0e2da5d228a,1e101e0daffaddce8159d25a8e53f2b2,delivered,2017-02-17 13:05:55,NaT,2017-02-22 11:23:11,2017-03-02 11:09:19,2017-03-20
26800,c1d4211b3dae76144deccd6c74144a88,684cb238dc5b5d6366244e0e0776b450,delivered,2017-01-19 12:48:08,NaT,2017-01-25 14:56:50,2017-01-30 18:16:01,2017-03-01
38290,d69e5d356402adc8cf17e08b5033acfb,68d081753ad4fe22fc4d410a9eb1ca01,delivered,2017-02-19 01:28:47,NaT,2017-02-23 03:11:48,2017-03-02 03:41:58,2017-03-27
39334,d77031d6a3c8a52f019764e68f211c69,0bf35cac6cc7327065da879e2d90fae8,delivered,2017-02-18 11:04:19,NaT,2017-02-23 07:23:36,2017-03-02 16:15:23,2017-03-22
48401,7002a78c79c519ac54022d4f8a65e6e8,d5de688c321096d15508faae67a27051,delivered,2017-01-19 22:26:59,NaT,2017-01-27 11:08:05,2017-02-06 14:22:19,2017-03-16
61743,2eecb0d85f281280f79fa00f9cec1a95,a3d3c38e58b9d2dfb9207cab690b6310,delivered,2017-02-17 17:21:55,NaT,2017-02-22 11:42:51,2017-03-03 12:16:03,2017-03-20
63052,51eb2eebd5d76a24625b31c33dd41449,07a2a7e0f63fd8cb757ed77d4245623c,delivered,2017-02-18 15:52:27,NaT,2017-02-23 03:09:14,2017-03-07 13:57:47,2017-03-29
67697,88083e8f64d95b932164187484d90212,f67cd1a215aae2a1074638bbd35a223a,delivered,2017-02-18 22:49:19,NaT,2017-02-22 11:31:06,2017-03-02 12:06:06,2017-03-21
72407,3c0b8706b065f9919d0505d3b3343881,d85919cb3c0529589c6fa617f5f43281,delivered,2017-02-17 15:53:27,NaT,2017-02-22 11:31:30,2017-03-03 11:47:47,2017-03-23
84999,2babbb4b15e6d2dfe95e2de765c97bce,74bebaf46603f9340e3b50c6b086f992,delivered,2017-02-18 17:15:03,NaT,2017-02-22 11:23:11,2017-03-03 18:43:43,2017-03-31

In [55]:
ordens_conjun_dados.loc[
    (ordens_conjun_dados['order_status'] == 'delivered') &
    (ordens_conjun_dados['order_approved_at'].isna()),
    'order_approved_at'
] = ordens_conjun_dados['order_purchase_timestamp']

In [56]:
df_nulos_filtro_created = df_nulos[df_nulos['order_status'] == 'created']
df_nulos_filtro_created

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
7434,b5359909123fa03c50bdb0cfed07f098,438449d4af8980d107bf04571413a8e7,created,2017-12-05 01:07:52,NaT,NaT,NaT,2018-01-11
9238,dba5062fbda3af4fb6c33b1e040ca38f,964a6df3d9bdf60fe3e7b8bb69ed893a,created,2018-02-09 17:21:04,NaT,NaT,NaT,2018-03-07
21441,7a4df5d8cff4090e541401a20a22bb80,725e9c75605414b21fd8c8d5a1c2f1d6,created,2017-11-25 11:10:33,NaT,NaT,NaT,2017-12-12
55086,35de4050331c6c644cddc86f4f2d0d64,4ee64f4bfc542546f422da0aeb462853,created,2017-12-05 01:07:58,NaT,NaT,NaT,2018-01-08
58958,90ab3e7d52544ec7bc3363c82689965f,7d61b9f4f216052ba664f22e9c504ef1,created,2017-11-06 13:12:34,NaT,NaT,NaT,2017-12-01

In [57]:
ordens_conjun_dados.duplicated().sum()

np.int64(0)

### Resultado

**Sobre as colunas do DF**

* Coluna **order_id**:
Representa o identificador unico do pedido.

* Coluna **customer_id**:
Representa o Id de cada pedido.

* Coluna **order_status**:
Representa o status do pedido, se foi enviado, cancelado e etc.

* Coluna **order_purchase_timestamp**:
Representa a data de carimbo da compra  

* Coluna **order_approved_at**:
Representa a data de aprovação do pedido 

* Coluna **order_delivered_carrier_date**:
Representa a data de entrega pela trasportadora

* Coluna **order_delivered_customer_date**:
Representa a data de entrega ao cliete 

* Coluna **order_estimated_delivery_date**:
Representa a data estimada de entrega

**Conclusão**

As colunas de datas estavam com o tipo de dado incorreto, então converti todas para **datetime64[ns]**.

Em seguida, identifiquei que algumas colunas — **order_approved_at, order_delivered_carrier_date e order_delivered_customer_date** — possuíam valores **nulos**. Analisei detalhadamente cada caso para definir o melhor tratamento:

os dados nulos vinham de 3 categorias de status diferentes

* Pedidos **cancelados**:

    Os valores nulos são esperados, pois não faz sentido um pedido cancelado ter datas de aprovação ou entrega.

    **Mantive os nulos**, pois podem ser úteis para **métricas futuras**.

* Pedidos **entregues (delivered)** com order_approved_at nulo:

    Indica **inconsistência**, pois um pedido entregue deveria ter data de aprovação.

    Para resolver, **substituí os nulos** pelo valor de **order_purchase_timestamp**, já que a aprovação geralmente ocorre logo após a compra.

* Pedidos **criados (created)** sem datas:

    Esses pedidos ainda **não foram aprovados ou confirmados**, então é natural que tenham datas nulas.

    **Mantive os nulos**, seguindo a mesma lógica dos pedidos cancelados.

Após essa análise, o DataFrame está com os tipos corretos, os valores nulos tratados de forma contextual e consistente, e pronto para as próximas etapas de análise ou ETL.

## Anali. conjunto produtos

In [58]:
produt_conjun_dados.head()

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
0,1e9e8ef04dbcff4541ed26657ea517e5,perfumaria,40.0,287.0,1.0,225.0,16.0,10.0,14.0
1,3aa071139cb16b67ca9e5dea641aaa2f,artes,44.0,276.0,1.0,1000.0,30.0,18.0,20.0
2,96bd76ec8810374ed1b65e291975717f,esporte_lazer,46.0,250.0,1.0,154.0,18.0,9.0,15.0
3,cef67bcfe19066a932b7673e239eb23d,bebes,27.0,261.0,1.0,371.0,26.0,4.0,26.0
4,9dc1a7de274444849c219cff195d0b71,utilidades_domesticas,37.0,402.0,4.0,625.0,20.0,17.0,13.0

In [59]:
produt_conjun_dados['product_category_name'].unique()

<StringArray>
[                                    'perfumaria',
                                          'artes',
                                  'esporte_lazer',
                                          'bebes',
                          'utilidades_domesticas',
                          'instrumentos_musicais',
                                     'cool_stuff',
                               'moveis_decoracao',
                               'eletrodomesticos',
                                     'brinquedos',
                                'cama_mesa_banho',
               'construcao_ferramentas_seguranca',
                         'informatica_acessorios',
                                   'beleza_saude',
                               'malas_acessorios',
                             'ferramentas_jardim',
                              'moveis_escritorio',
                                     'automotivo',
                                    'eletronicos',
                               'fashion_calcados',
                                      'telefonia',
                                      'papelaria',
                    'fashion_bolsas_e_acessorios',
                                            'pcs',
                                'casa_construcao',
                             'relogios_presentes',
              'construcao_ferramentas_construcao',
                                       'pet_shop',
                                'eletroportateis',
                      'agro_industria_e_comercio',
                                              nan,
                                    'moveis_sala',
                        'sinalizacao_e_seguranca',
                                   'climatizacao',
                                 'consoles_games',
                         'livros_interesse_geral',
             'construcao_ferramentas_ferramentas',
                 'fashion_underwear_e_moda_praia',
                        'fashion_roupa_masculina',
 'moveis_cozinha_area_de_servico_jantar_e_jardim',
                  'industria_comercio_e_negocios',
                                 'telefonia_fixa',
              'construcao_ferramentas_iluminacao',
                                'livros_tecnicos',
                             'eletrodomesticos_2',
                              'artigos_de_festas',
                                        'bebidas',
                                   'market_place',
                                     'la_cuisine',
                  'construcao_ferramentas_jardim',
                         'fashion_roupa_feminina',
                                  'casa_conforto',
                                          'audio',
                              'alimentos_bebidas',
                                         'musica',
                                      'alimentos',
                       'tablets_impressao_imagem',
                              'livros_importados',
                    'portateis_casa_forno_e_cafe',
                                'fashion_esporte',
                               'artigos_de_natal',
                  'fashion_roupa_infanto_juvenil',
                                   'dvds_blu_ray',
                             'artes_e_artesanato',
                                       'pc_gamer',
                                  'moveis_quarto',
                                      'cine_foto',
                                'fraldas_higiene',
                                         'flores',
                                'casa_conforto_2',
  'portateis_cozinha_e_preparadores_de_alimentos',
                             'seguros_e_servicos',
                      'moveis_colchao_e_estofado',
                              'cds_dvds_musicais']
Length: 74, dtype: str

In [60]:
produt_conjun_dados.info()

<class 'pandas.DataFrame'>
RangeIndex: 32951 entries, 0 to 32950
Data columns (total 9 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   product_id                  32951 non-null  str
 1   product_category_name       32341 non-null  str
 2   product_name_lenght         32341 non-null  float64
 3   product_description_lenght  32341 non-null  float64
 4   product_photos_qty          32341 non-null  float64
 5   product_weight_g            32949 non-null  float64
 6   product_length_cm           32949 non-null  float64
 7   product_height_cm           32949 non-null  float64
 8   product_width_cm            32949 non-null  float64
dtypes: float64(7), str(2)
memory usage: 2.3 MB

In [61]:
produt_conjun_dados['product_name_lenght'] = produt_conjun_dados['product_name_lenght'].astype('Int64')
produt_conjun_dados['product_description_lenght'] = produt_conjun_dados['product_description_lenght'].astype('Int64')
produt_conjun_dados['product_photos_qty'] = produt_conjun_dados['product_photos_qty'].astype('Int64')

In [62]:
produt_conjun_dados.isnull().sum()

product_id                      0
product_category_name         610
product_name_lenght           610
product_description_lenght    610
product_photos_qty            610
product_weight_g                2
product_length_cm               2
product_height_cm               2
product_width_cm                2
dtype: int64

In [63]:
df_nulos_products = produt_conjun_dados[
    produt_conjun_dados['product_name_lenght'].isnull()]
df_nulos_products.head()

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
105,a41e356c76fab66334f36de622ecbd3a,NaN,<NA>,<NA>,<NA>,650.0,17.0,14.0,12.0
128,d8dee61c2034d6d075997acef1870e9b,NaN,<NA>,<NA>,<NA>,300.0,16.0,7.0,20.0
145,56139431d72cd51f19eb9f7dae4d1617,NaN,<NA>,<NA>,<NA>,200.0,20.0,20.0,20.0
154,46b48281eb6d663ced748f324108c733,NaN,<NA>,<NA>,<NA>,18500.0,41.0,30.0,41.0
197,5fb61f482620cb672f5e586bb132eae9,NaN,<NA>,<NA>,<NA>,300.0,35.0,7.0,12.0

In [64]:
produt_conjun_dados['product_category_name'] = produt_conjun_dados['product_category_name'].fillna('unknown')
produt_conjun_dados['product_photos_qty'] = produt_conjun_dados['product_photos_qty'].fillna(0)

In [65]:
df_nulos_products = produt_conjun_dados[
    produt_conjun_dados['product_weight_g'].isnull()]
df_nulos_products.head()

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
8578,09ff539a621711667c43eba6a3bd8466,bebes,60,865,3,NaN,NaN,NaN,NaN
18851,5eb564652db742ff8f28759cd8d2652a,unknown,<NA>,<NA>,0,NaN,NaN,NaN,NaN

In [66]:
produt_conjun_dados.duplicated().sum()

np.int64(0)

### Resultado

**Sobre as colunas do DF**

* Coluna **product_id**:
Representa o Id do produto

* Coluna **product_category_name**:
Representa o nome da categoria do produto

* Coluna **product_name_lenght**:
Representa o compriomento do nome do produto

* Coluna **product_description_lenght**:
Representa o comprimento da descrição do produto

* Coluna **product_photos_qty**:
Representa a quantidade de fotos do produto

* Coluna **product_weight_g**:
Representa o peso do produto em g 

* Coluna **product_length_cm**:
Representa o comprimento do produto em cm 

* Coluna **product_height_cm**:
Representa a altura do produto em cm

* Coluna **product_width_cm**:
Representa a largura do produto edm cm

**Conclusão**

As colunas **product_name_lenght**, **product_description_lenght** e **product_photos_qty** estavam com o tipo de dado incorreto, portanto converti todas para o tipo **Int64**, garantindo que os valores fossem tratados como números inteiros e permitindo a manutenção de valores nulos quando necessário.

Durante a análise, identifiquei a presença de **valores nulos** em algumas colunas.

Na coluna **product_category_name**, optei por criar uma nova categoria chamada **"unknown"** para substituir os valores nulos, pois não seria possível identificar corretamente a categoria desses produtos.

Já nas colunas **product_name_lenght** e **product_description_lenght**, decidi manter os valores nulos, pois não havia informações suficientes para estimar esses dados sem **comprometer a integridade da base**.

No caso da coluna **product_photos_qty**, os valores nulos foram **substituídos por 0**, interpretando que esses produtos não possuem fotos cadastradas.

Com isso, a base foi tratada de forma consistente, mantendo a integridade dos dados e preparando o DataFrame para as próximas etapas.

## Anali. conjunto vendedores

In [67]:
vendedores_conjun_dados.head()

,seller_id,seller_zip_code_prefix,seller_city,seller_state
0,3442f8959a84dea7ee197c632cb2df15,13023,campinas,SP
1,d1b65fc7debc3361ea86b5f14c68d2e2,13844,mogi guacu,SP
2,ce3ad9de960102d0677a81f5d0bb7b2d,20031,rio de janeiro,RJ
3,c0f3eea2e14555b6faeea3dd58c1b1c3,4195,sao paulo,SP
4,51a04a8a6bdcb23deccc82b0b80742cf,12914,braganca paulista,SP

In [69]:
vendedores_conjun_dados.info()

<class 'pandas.DataFrame'>
RangeIndex: 3095 entries, 0 to 3094
Data columns (total 4 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   seller_id               3095 non-null   str
 1   seller_zip_code_prefix  3095 non-null   int64
 2   seller_city             3095 non-null   str
 3   seller_state            3095 non-null   str
dtypes: int64(1), str(3)
memory usage: 96.8 KB

In [70]:
vendedores_conjun_dados.isnull().sum()

seller_id                 0
seller_zip_code_prefix    0
seller_city               0
seller_state              0
dtype: int64

In [71]:
vendedores_conjun_dados.duplicated().sum()

np.int64(0)

### Resultado

**Sobre as colunas do DF**

* Coluna **seller_id**:
Representra o id dos vendedors

* Coluna **seller_zip_code_prefix**:
Representa o prefixo do  codigo postal do vendedor

* Coluna **seller_city**:
Representa a cidade que reside o vendedor

* Coluna **seller_state**:
Representa o estado que o vendedor reside

**Conclusão**

Neste conjunto de dados não foi necessario fazer **nenhuma alteração ou correção**, pois os **tipos de dados** estão **corretos**, não possui **nenhum** valor **nulo ou duplicado**.

## Anali. conjunto produtos_categorias_nomes_transações

In [72]:
Produt_categ_nome_transacao.head()

    product_category_name product_category_name_english
0            beleza_saude                 health_beauty
1  informatica_acessorios         computers_accessories
2              automotivo                          auto
3         cama_mesa_banho                bed_bath_table
4        moveis_decoracao               furniture_decor

In [73]:
Produt_categ_nome_transacao.info()

<class 'pandas.DataFrame'>
RangeIndex: 71 entries, 0 to 70
Data columns (total 2 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   product_category_name          71 non-null     str
 1   product_category_name_english  71 non-null     str
dtypes: str(2)
memory usage: 1.2 KB

In [74]:
Produt_categ_nome_transacao['product_category_name'].unique()

<StringArray>
[                                  'beleza_saude',
                         'informatica_acessorios',
                                     'automotivo',
                                'cama_mesa_banho',
                               'moveis_decoracao',
                                  'esporte_lazer',
                                     'perfumaria',
                          'utilidades_domesticas',
                                      'telefonia',
                             'relogios_presentes',
                              'alimentos_bebidas',
                                          'bebes',
                                      'papelaria',
                       'tablets_impressao_imagem',
                                     'brinquedos',
                                 'telefonia_fixa',
                             'ferramentas_jardim',
                    'fashion_bolsas_e_acessorios',
                                'eletroportateis',
                                 'consoles_games',
                                          'audio',
                               'fashion_calcados',
                                     'cool_stuff',
                               'malas_acessorios',
                                   'climatizacao',
              'construcao_ferramentas_construcao',
 'moveis_cozinha_area_de_servico_jantar_e_jardim',
                  'construcao_ferramentas_jardim',
                        'fashion_roupa_masculina',
                                       'pet_shop',
                              'moveis_escritorio',
                                   'market_place',
                                    'eletronicos',
                               'eletrodomesticos',
                              'artigos_de_festas',
                                  'casa_conforto',
             'construcao_ferramentas_ferramentas',
                      'agro_industria_e_comercio',
                      'moveis_colchao_e_estofado',
                                'livros_tecnicos',
                                'casa_construcao',
                          'instrumentos_musicais',
                                    'moveis_sala',
              'construcao_ferramentas_iluminacao',
                  'industria_comercio_e_negocios',
                                      'alimentos',
                                          'artes',
                                  'moveis_quarto',
                         'livros_interesse_geral',
               'construcao_ferramentas_seguranca',
                 'fashion_underwear_e_moda_praia',
                                'fashion_esporte',
                        'sinalizacao_e_seguranca',
                                            'pcs',
                               'artigos_de_natal',
                         'fashion_roupa_feminina',
                             'eletrodomesticos_2',
                              'livros_importados',
                                        'bebidas',
                                      'cine_foto',
                                     'la_cuisine',
                                         'musica',
                                'casa_conforto_2',
                    'portateis_casa_forno_e_cafe',
                              'cds_dvds_musicais',
                                   'dvds_blu_ray',
                                         'flores',
                             'artes_e_artesanato',
                                'fraldas_higiene',
                  'fashion_roupa_infanto_juvenil',
                             'seguros_e_servicos']
Length: 71, dtype: str

In [77]:
Produt_categ_nome_transacao.isnull().sum()

product_category_name            0
product_category_name_english    0
dtype: int64

In [79]:
Produt_categ_nome_transacao.duplicated().sum()

np.int64(0)

### Resultado

**Sobre as colunas do DF**

* Coluna **product_category_name**:
Representa os nomes das categorias dos produtos.


* Coluna **product_category_name_english**:
Representa os nomes das categorias dos produtos em inglês.

**Conclusão**


Neste conjunto de dados não foi necessario fazer **nenhuma alteração ou correção**, pois os **tipos de dados** estão **corretos**, não possui **nenhum** valor **nulo ou duplicado**.